#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Jan 10 17:50:31 MST 2023
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 7bf5cd5f77d64151943fe37bcf3d8695 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot UpDownButtonCount_behav xil_defaultlib.UpDownButtonCount xil_defaultlib.glbl -log elaborate.log"
xelab -wto 7bf5cd5f77d64151943fe37bcf3d8695 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip --snapshot UpDownButtonCount_behav xil_defaultlib.UpDownButtonCount xil_defaultlib.glbl -log elaborate.log

